
const Map<String, String> en = {
  "oops": "Oops!",
  "something_wrong": "Something went wrong",
  "welcome": "Welcome %s",
  "app_name": "VACC+ID",
  "scan": "Scan",
  "info": "Info",
  "history": "History",
  "history_scanners": "History Of Scanners",
  "delete_item": "Delete Item",
  "delete": "Delete",
  "cancel": "Cancel",
  "confirm_delete": "Are you sure you want to delete %s",
  "information": "Information",
  "license": "License",
  "copyright": "Copyright 2021 Roger Nesbitt",
  "permission_hereby": """Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated documentation files (the "Software"), to deal in the Software without restriction, including without limitation the rights to use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of the Software, and to permit persons to whom the Software is furnished to do so, subject to the following conditions:""",
  "above_copyright": "The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.",
  "software_provided": """THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.""",
  "logout": "Log Out",
  "rate_app": "Rate us ⭐⭐⭐⭐⭐",
  "clear_history": "Clear history",
  "clear_history_msg": "Are you sure you want to clear all the history",
  "clear": "Clear",
  "privacy": "Privacy",
  "version": "Version %s",
  "saved_success": "Saved successfully",
  "exit_app": "Are you sure you want to exit?",
  "exit": "Exit",
  "scan_vaccine": "Scan vaccine",
  "scan_locations": "Scan locations",
  "type_scan": "Choose the type scan",
  "vaccines": "Vaccines",
  "locations": "Locations",
  "upload_profile_pic": "Upload your profile picture",
  "id_photo": "ID Photo",
  "add_license_or_id": "Add your license or state ID",
  "add_license_id": "Add license or ID",
  "update_license_id": "Update license or ID",
  "photo_library": "Photo Library",
  "take_photo": "Take Photo",
  "crop_rotate": "Crop and rotate",
  "ok": "Ok",
  "verification": "Verification",
  "pin_not_match": "PIN does not match",
  "set_pin": "Set PIN code",
  "update_pin": "Update PIN code",
  "field_required": "field required",
  "prompted_enter_pin": "You'll be prompted to enter PIN code each time you open the App",
  "enter_pin": "Enter PIN Code",
  "confirm_pin": "Confirm PIN Code",
  "enter_your_pin": "Enter your PIN Code",
  "enter_digit_pin": "please enter the four digit PIN code",
  "pin_code": "PIN Code",
  "activate_deactivate_pin": "Activate / Deactivate",

};